float: "Vinyl Guardian"
description: "false to ADC line-in, fingerprints audio via AcoustID, and updates HA via MQTT."
version: "1.2.12"
slug: "vinyl_guardian"
init: false
arch:
  - aarch64
  - amd64
  - armv7
audio: true
devices:
  - /dev/snd:/dev/snd:rwm
startup: application
boot: auto
# This schema creates the Configuration UI boxes in Home Assistant
schema:
  acoustid_key: str
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: password?
  audio_threshold: float
  mic_volume: int(0, 100)
  debug_logging: bool
# These are the default values shown to users
options:
  acoustid_key: ""
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  audio_threshold: 0.015
  mic_volume: 10
  debug_logging: false
