const { chromium }=require('playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const path=require('node:path');
const fs=require('node:fs');
const port=process.env.AUDIOSHELF_TEST_PORT||'8102';
const base=`http://127.0.0.1:${port}`;
const server=spawn(process.env.AUDIOSHELF_TEST_PYTHON||'python',[path.join(__dirname,'ui_server.py')],{env:{...process.env,AUDIOSHELF_TEST_PORT:port,AUDIOSHELF_TEST_VINYL:'1'},stdio:['ignore','pipe','pipe']});
let logs='';server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const screenshots=process.env.AUDIOSHELF_SCREENSHOT_DIR;
(async()=>{
  let browser;
  try{
    let ready=false;
    for(let n=0;n<80;n++){try{if((await fetch(base+'/health')).ok){ready=true;break;}}catch{}await wait(100);}
    assert(ready,logs);
    browser=await chromium.launch({headless:true,executablePath:process.env.AUDIOSHELF_TEST_BROWSER||undefined,args:process.env.AUDIOSHELF_TEST_BROWSER?['--no-sandbox','--disable-dev-shm-usage']:[]});
    const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
    const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
    page.on('request',r=>{if(r.url().includes('/api/'))requests.push('START '+r.method()+' '+new URL(r.url()).pathname);});
    page.on('response',r=>{if(r.url().includes('/api/'))requests.push('END '+r.status()+' '+new URL(r.url()).pathname);});
    async function waitPlaying(){
      try{await page.locator('#turntable small b').filter({hasText:'PLAYING'}).waitFor();}
      catch(error){console.error(JSON.stringify({errors,requests:requests.slice(-30),state:await page.evaluate(()=>({toast:document.querySelector('#toast').textContent,turntable:document.querySelector('#turntable').textContent,playbackState,playbackBusy,pendingPlayback,checkingPlayback}))}));throw error;}
    }
    // Synthetic covers keep screenshots reproducible, with no third-party downloads.
    await page.route('**/api/albums/*/artwork?*',async route=>{
      const key=route.request().url().split('/albums/')[1].split('/')[0];
      const index=Array.from(key).reduce((sum,c)=>sum+c.charCodeAt(0),0)%18;
      const response=await fetch(base+'/__test/vinyl-cover/'+index);
      await route.fulfill({contentType:'image/png',body:Buffer.from(await response.arrayBuffer())});
    });
    async function shot(name){if(screenshots){fs.mkdirSync(screenshots,{recursive:true});await page.screenshot({path:path.join(screenshots,'vinyl-'+name+'.png'),fullPage:true});}}
    async function noOverflow(){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Horizontal overflow at '+page.url());}
    await page.goto(base);
    await page.getByLabel('Password',{exact:true}).fill('fixture-owner-password');
    await page.getByRole('button',{name:'Open AudioShelf',exact:true}).click();
    await page.locator('.shelf-rack').first().waitFor();
    assert.equal(await page.locator('.sleeve').count(),14);
    assert.equal(await page.locator('html').getAttribute('data-interface'),'vinyl');
    // External artist links retain the full shelf and land at the artist section.
    await page.goto(base+'/#shelf/f181961b-20f7-459e-89de-920ef03c7ed0');
    await page.locator('[data-shelf-id]').first().waitFor();
    await page.waitForFunction(()=>Math.abs(document.querySelector('[data-shelf-id]').getBoundingClientRect().top-parseFloat(getComputedStyle(document.documentElement).scrollPaddingTop))<3);
    assert.equal(await page.locator('.sleeve').count(),14);
    await page.goto(base+'/#store/artist/The%20Artist');
    await page.locator('.artist-bin').first().waitFor();
    assert.equal(await page.locator('#search-form input').inputValue(),'The Artist');
    await page.goto(base+'/#shelf');
    await page.locator('.shelf-rack').first().waitFor();
    await page.locator('.cover').first().evaluate(img=>img.decode());
    await noOverflow();await shot('shelf-desktop');
    await page.getByRole('searchbox',{name:'Find a record'}).fill('does not exist');
    assert.equal(await page.locator('.sleeve:visible').count(),0);
    await page.getByRole('searchbox',{name:'Find a record'}).fill('');
    const sleeve=page.locator('.sleeve .album-title').last();
    const inspected=await sleeve.textContent();
    await sleeve.scrollIntoViewIfNeeded();
    const scroll=await page.evaluate(()=>scrollY);assert(scroll>300);
    await sleeve.click();await page.getByRole('heading',{name:inspected,exact:true}).waitFor();
    await page.getByRole('link',{name:'Back to browsing'}).click();
    await page.locator('.shelf-rack').first().waitFor();
    await page.waitForFunction(y=>Math.abs(scrollY-y)<3,scroll);
    // Compact shelves preserve covers, search and browsing without showing every artist.
    await page.getByRole('button',{name:'Artist dividers',exact:true}).click();
    assert.equal(await page.locator('.sleeve:visible').count(),0);
    const dividers=page.locator('.shelf-artist-toggle');
    assert.equal(await dividers.count(),2);
    await dividers.first().click();
    assert.equal(await page.locator('.shelf-artist-toggle[aria-expanded="true"]').count(),1);
    assert((await page.locator('.sleeve:visible').count())>0);
    await dividers.last().click();
    assert.equal(await dividers.first().getAttribute('aria-expanded'),'false');
    assert.equal(await dividers.last().getAttribute('aria-expanded'),'true');
    const openId=await dividers.last().evaluate(el=>el.closest('[data-shelf-id]').dataset.shelfId);
    const compactAlbum=page.locator('.sleeve:visible .album-title').first();
    const compactTitle=await compactAlbum.textContent();
    await compactAlbum.click();
    await page.getByRole('heading',{name:compactTitle,exact:true}).waitFor();
    await page.getByRole('link',{name:'Back to browsing'}).click();
    await page.locator('.shelf-artist-toggle[aria-expanded="true"]').waitFor();
    assert.equal(await page.locator('.shelf-artist-toggle[aria-expanded="true"]').evaluate(el=>el.closest('[data-shelf-id]').dataset.shelfId),openId);
    await page.getByRole('searchbox',{name:'Find a record'}).fill('does not exist');
    await page.locator('#shelf-no-results').waitFor();
    assert.equal(await page.locator('.shelf-artist-toggle:visible').count(),0);
    await page.getByRole('searchbox',{name:'Find a record'}).fill(compactTitle);
    assert.equal(await page.locator('.sleeve:visible').count(),1);
    await page.getByRole('searchbox',{name:'Find a record'}).fill('');
    await noOverflow();await shot('dividers-desktop');
    await page.reload();
    await page.locator('.collection-shelves[data-layout="dividers"]').waitFor();
    assert.equal(await page.locator('.sleeve:visible').count(),0,'A fresh visit starts with dividers closed');
    await page.goto(base+'/#shelf/'+openId);
    await page.locator('.shelf-artist-toggle[aria-expanded="true"]').waitFor();
    assert.equal(await page.locator('.shelf-artist-toggle[aria-expanded="true"]').evaluate(el=>el.closest('[data-shelf-id]').dataset.shelfId),openId);
    await page.setViewportSize({width:390,height:844});
    await noOverflow();await shot('dividers-mobile');
    await dividers.last().click();
    await dividers.last().focus();await page.keyboard.press('Enter');
    assert.equal(await dividers.last().getAttribute('aria-expanded'),'true','Keyboard opens the divider');
    await page.setViewportSize({width:320,height:740});await noOverflow();
    await page.getByRole('button',{name:'Open shelves',exact:true}).click();
    assert.equal(await page.locator('.sleeve:visible').count(),14);
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('[data-nav="store"]').click();
    await page.getByRole('button',{name:'Albums',exact:true}).click();
    await page.getByRole('searchbox',{name:'Search record store'}).fill('all records');
    await page.getByRole('button',{name:'Search',exact:true}).click();
    await page.locator('.store-rack').first().waitFor();
    assert.equal(await page.locator('.sleeve').count(),17);
    await noOverflow();await shot('store-desktop');
    await page.getByRole('button',{name:'Add Open Windows to shelf',exact:true}).click();
    await page.locator('#toast').filter({hasText:'Open Windows added'}).waitFor();
    assert(page.url().endsWith('#store'));
    await page.getByRole('link',{name:'Open Windows',exact:true}).click();
    await page.getByRole('heading',{name:'Open Windows',exact:true}).waitFor();
    await page.getByRole('link',{name:'Back to browsing'}).click();
    await page.locator('.store-rack').first().waitFor();
    assert.equal(await page.getByRole('searchbox',{name:'Search record store'}).inputValue(),'all records');
    assert.equal(await page.locator('.sleeve').count(),17);
    assert.equal(await page.getByRole('button',{name:'Add Open Windows to shelf',exact:true}).count(),0);
    await page.getByRole('link',{name:'The Original Album',exact:true}).click();
    await page.getByRole('button',{name:'This tracklist is correct'}).click();
    await page.getByRole('button',{name:'This tracklist is correct'}).waitFor({state:'hidden'});
    // Spotify can briefly return the old song after accepting a new queue.
    let startupReads=0, confirmStartup;
    const startupGate=new Promise(resolve=>confirmStartup=resolve);
    await page.evaluate(()=>playbackChecked=Date.now());
    await page.route('**/api/spotify/playback',async route=>{
      startupReads++;
      if(startupReads===1){await route.fulfill({contentType:'application/json',body:JSON.stringify({active:true,playing:true,track:'Previous song',track_ids:['old-track'],progress_ms:120000,duration_ms:180000,album:'Previous album'})});return;}
      if(startupReads===2){await route.fulfill({contentType:'application/json',body:JSON.stringify({active:true,playing:true,track:'Opening',track_ids:['a'.repeat(22)],progress_ms:120000,duration_ms:180000,album:'The Original Album'})});return;}
      await startupGate;await route.continue();
    });
    await page.getByRole('button',{name:'Play album',exact:false}).click();
    await page.getByRole('heading',{name:'Choose playback device',exact:true}).waitFor();
    await page.getByRole('button',{name:'Fixture phone',exact:false}).click();
    await page.locator('#turntable small b').filter({hasText:'STARTING'}).waitFor();
    assert.equal(await page.locator('#turntable strong').textContent(),'The Original Album');
    assert((await page.locator('#turntable .turntable-record').textContent()).includes('Opening'));
    assert.equal(await page.getByRole('progressbar',{name:'Song progress'}).evaluate(el=>el.value),0);
    await page.waitForFunction(()=>document.querySelector('#turntable small b')?.textContent==='STARTING');
    confirmStartup();
    await page.locator('#turntable small b').filter({hasText:'PLAYING'}).waitFor({timeout:4000});
    assert(startupReads>=3,'Startup retries must not wait for the normal poll');
    await page.unroute('**/api/spotify/playback');
    const initialProgress=await page.getByRole('progressbar',{name:'Song progress'}).evaluate(el=>el.value);
    await page.waitForFunction(start=>document.querySelector('#turntable progress')?.value>start+500,initialProgress);
    assert.equal(await page.getByRole('progressbar',{name:'Song progress'}).evaluate(el=>el.max),180000);
    assert.equal(await page.locator('#turntable strong').textContent(),'The Original Album');
    await noOverflow();await shot('album-desktop');
    // A late Play response must never replace the newly inspected sleeve.
    let releasePlay, playReceived;
    const received=new Promise(resolve=>playReceived=resolve);
    const release=new Promise(resolve=>releasePlay=resolve);
    await page.route('**/api/albums/*/play',async route=>{playReceived();await release;const response=await route.fetch();await route.fulfill({response});});
    await page.getByRole('button',{name:'Play album',exact:false}).click();
    await received;
    assert.equal(await page.locator('#turntable small b').textContent(),'STARTING','Requested song must appear before the playback API responds');
    assert((await page.locator('#turntable .turntable-record').textContent()).includes('Opening'));
    await page.getByRole('link',{name:'Back to browsing'}).click();
    await page.getByRole('link',{name:'First Light',exact:true}).click();
    releasePlay();
    await page.unroute('**/api/albums/*/play');
    await page.getByRole('heading',{name:'First Light',exact:true}).waitFor();
    await waitPlaying();
    assert.equal(await page.locator('#turntable strong').textContent(),'The Original Album');
    assert.equal(await page.getByRole('heading',{name:'First Light',exact:true}).count(),1);
    await page.getByRole('button',{name:'Album settings'}).click();
    await page.getByRole('button',{name:'Choose cover from another edition'}).waitFor();
    await page.getByRole('link',{name:'Download diagnostic report'}).waitFor();
    await page.getByRole('button',{name:'Close',exact:true}).click();
    await page.setViewportSize({width:390,height:844});
    await noOverflow();await shot('album-mobile');
    await page.locator('[data-nav="shelf"]').click();
    await page.locator('.shelf-rack').first().waitFor();
    assert.equal(await page.locator('.sleeve').count(),15);
    assert.equal(await page.locator('.shelf-rack').first().evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),2);
    await noOverflow();await shot('shelf-mobile');
    await page.locator('[data-nav="store"]').click();
    await page.locator('.store-rack').first().waitFor();
    await noOverflow();await shot('store-mobile');
    await page.route('**/api/spotify/playback',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({active:true,playing:false,album:'The Original Album',album_id:'f5093c06-23e3-4f01-aeaa-40f72885ee3a',track:'Opening',artist:'The Artist',device:'Phone',progress_ms:42000,duration_ms:180000,track_ids:['a'.repeat(22)]})}));
    await page.evaluate(()=>refreshPlayback(true));
    await page.locator('#turntable small b').filter({hasText:'PAUSED'}).waitFor();
    assert.equal(await page.getByRole('progressbar',{name:'Song progress'}).evaluate(el=>el.value),42000);
    const progressNode=await page.locator('#turntable progress').elementHandle();
    await page.waitForFunction(()=>document.querySelector('#turntable [data-elapsed]')?.textContent==='0:42');
    await page.evaluate(()=>{playbackState.observedAt-=10000;updateTrackProgress();});
    assert.equal(await progressNode.evaluate(el=>el.value),42000,'Paused progress must not advance');
    await noOverflow();await shot('progress-mobile');
    await page.unroute('**/api/spotify/playback');
    await page.route('**/api/spotify/playback',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Unavailable'})}));
    await page.evaluate(()=>refreshPlayback(true));
    await page.locator('#turntable small b').filter({hasText:'STATUS UNAVAILABLE'}).waitFor();
    await page.unroute('**/api/spotify/playback');
    // At a song boundary refresh promptly instead of leaving a full bar and old title.
    let boundaryReads=0;
    await page.route('**/api/spotify/playback',route=>{boundaryReads++;return route.fulfill({contentType:'application/json',body:JSON.stringify({active:true,playing:true,track:'Closing',album:'The Original Album',progress_ms:1000,duration_ms:240000,track_ids:['b'.repeat(22)]})});});
    await page.evaluate(()=>{
      playbackState={active:true,playing:true,track:'Opening',album:'The Original Album',progress_ms:179900,duration_ms:180000,observedAt:performance.now()};
      playbackChecked=Date.now()-1100;renderTurntable();
    });
    await page.waitForFunction(()=>document.querySelector('#turntable .turntable-record')?.textContent.includes('Closing'),null,{timeout:2500});
    assert(boundaryReads>0);
    assert.equal(await page.getByRole('progressbar',{name:'Song progress'}).evaluate(el=>el.max),240000);
    await page.unroute('**/api/spotify/playback');
    await page.getByRole('link',{name:'Open settings'}).click();
    await page.getByRole('button',{name:'Classic The original AudioShelf interface',exact:false}).click();
    await page.locator('html[data-interface="classic"]').waitFor();
    assert.equal(await page.locator('#turntable').isVisible(),false);
    await page.reload();await page.getByRole('heading',{name:'Settings.'}).waitFor();
    assert.equal(await page.locator('html').getAttribute('data-interface'),'classic');
    await page.locator('[data-nav="shelf"]').click();
    await page.locator('.artist-row').first().waitFor();
    await page.getByRole('link',{name:'Open settings'}).click();
    await page.getByRole('button',{name:'Vinyl Front-facing sleeves',exact:false}).click();
    await page.locator('html[data-interface="vinyl"]').waitFor();
    await page.setViewportSize({width:320,height:740});await noOverflow();
    await page.locator('[data-nav="shelf"]').click();await page.locator('.shelf-rack').first().waitFor();await noOverflow();
    assert.deepEqual(errors,[]);
    console.log('Vinyl browser checks passed: two rooms, responsive sleeves, browsing restoration, collect in place, rapid startup despite stale replies, progress/pause/track boundaries, playback independence/outage, album settings, Classic persistence.');
  }finally{if(browser)await browser.close();server.kill('SIGTERM');}
})().catch(error=>{console.error(error);console.error(logs.slice(-4000));process.exitCode=1;});
