name: Python Venv SSH
version: "1.0.3"
slug: python_venv_ssh
description: SSH into a container with a fresh Python virtual environment each session
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
host_network: true
ports:
  2222/tcp: 2222
map:
  - config:rw
  - share:rw
options:
  ssh_user: dev
  ssh_password: dev
schema:
  ssh_user: str
  ssh_password: str
