const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
  const browser = await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || undefined,args:['--no-sandbox','--ignore-certificate-errors']});
  const page = await browser.newPage({ignoreHTTPSErrors:true,viewport:{width:390,height:844}});
  const root = process.env.AUTH_APP_URL || 'https://127.0.0.1:8107';
  await page.goto(root);
  await page.getByLabel('Password',{exact:true}).fill('incorrect');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('alert').waitFor();
  await page.getByLabel('Password',{exact:true}).fill('fictional-test-password');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.locator('#content .metrics').waitFor();
  const manifest = await page.evaluate(async()=>await (await fetch('manifest.webmanifest')).json());
  assert.equal(manifest.display,'standalone');
  assert.equal(manifest.start_url,'/');
  await page.waitForFunction(async()=>!!(await navigator.serviceWorker.getRegistration()));
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
  const cookies = await page.context().cookies();
  const cookie = cookies.find(c=>c.name==='listening_session');
  assert.ok(cookie.secure && cookie.httpOnly);
  assert.equal(await page.locator('#logout').isVisible(), false);
  await page.locator('.settings-nav').click();
  await page.locator('#logout').click();
  await page.getByRole('button',{name:'Sign in',exact:true}).waitFor();
  assert.equal((await page.request.get(root+'/api/status')).status(),401);
  await page.goto(root);
  await page.getByRole('button',{name:'Sign in',exact:true}).waitFor();
  await page.screenshot({path:process.env.LOGIN_SCREENSHOT || '/tmp/listening-analytics-login.png',fullPage:true});
  await browser.close();
  console.log('HTTPS browser login, secure cookies, PWA manifest, service worker and logout passed.');
})().catch(e=>{console.error(e);process.exit(1)});
